name = "portsindex-proxy"
main = "dist/proxy.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[env.production]
workers_dev = true
route = { pattern = "portsindex-proxy.sahaibsingh001-ss.workers.dev", custom_domain = true }