export const PROXY_URL = '/api/proxy';

export const CLIENT_HEADERS = {
  'Accept': 'text/html,application/xhtml+xml',
};

export const BASE_URL = '';

export const SUPPORTED_COUNTRIES = {
  'AF': { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', endpoint: '/af.htm' },
  'AX': { code: 'AX', name: 'Åland Islands', flag: '🇦🇽', endpoint: '/ax.htm' },
  'AL': { code: 'AL', name: 'Albania', flag: '🇦🇱', endpoint: '/al.htm' },
  'DZ': { code: 'DZ', name: 'Algeria', flag: '🇩🇿', endpoint: '/dz.htm' },
  'AS': { code: 'AS', name: 'American Samoa', flag: '🇦🇸', endpoint: '/as.htm' },
  'AD': { code: 'AD', name: 'Andorra', flag: '🇦🇩', endpoint: '/ad.htm' },
  'AO': { code: 'AO', name: 'Angola', flag: '🇦🇴', endpoint: '/ao.htm' },
  'AI': { code: 'AI', name: 'Anguilla', flag: '🇦🇮', endpoint: '/ai.htm' },
  'AQ': { code: 'AQ', name: 'Antarctica', flag: '🇦🇶', endpoint: '/aq.htm' },
  'AG': { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', endpoint: '/ag.htm' },
  'AR': { code: 'AR', name: 'Argentina', flag: '🇦🇷', endpoint: '/ar.htm' },
  'AM': { code: 'AM', name: 'Armenia', flag: '🇦🇲', endpoint: '/am.htm' },
  'AW': { code: 'AW', name: 'Aruba', flag: '🇦🇼', endpoint: '/aw.htm' },
  'AU': { code: 'AU', name: 'Australia', flag: '🇦🇺', endpoint: '/au.htm' },
  'AT': { code: 'AT', name: 'Austria', flag: '🇦🇹', endpoint: '/at.htm' },
  'AZ': { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', endpoint: '/az.htm' },
  'BS': { code: 'BS', name: 'Bahamas', flag: '🇧🇸', endpoint: '/bs.htm' },
  'BH': { code: 'BH', name: 'Bahrain', flag: '🇧🇭', endpoint: '/bh.htm' },
  'BD': { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', endpoint: '/bd.htm' },
  'BB': { code: 'BB', name: 'Barbados', flag: '🇧🇧', endpoint: '/bb.htm' },
  'BY': { code: 'BY', name: 'Belarus', flag: '🇧🇾', endpoint: '/by.htm' },
  'BE': { code: 'BE', name: 'Belgium', flag: '🇧🇪', endpoint: '/be.htm' },
  'BZ': { code: 'BZ', name: 'Belize', flag: '🇧🇿', endpoint: '/bz.htm' },
  'BJ': { code: 'BJ', name: 'Benin', flag: '🇧🇯', endpoint: '/bj.htm' },
  'BM': { code: 'BM', name: 'Bermuda', flag: '🇧🇲', endpoint: '/bm.htm' },
  'BT': { code: 'BT', name: 'Bhutan', flag: '🇧🇹', endpoint: '/bt.htm' },
  'BO': { code: 'BO', name: 'Bolivia', flag: '🇧🇴', endpoint: '/bo.htm' },
  'BQ': { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', flag: '🇧🇶', endpoint: '/bq.htm' },
  'BA': { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', endpoint: '/ba.htm' },
  'BW': { code: 'BW', name: 'Botswana', flag: '🇧🇼', endpoint: '/bw.htm' },
  'BV': { code: 'BV', name: 'Bouvet Island', flag: '🇧🇻', endpoint: '/bv.htm' },
  'BR': { code: 'BR', name: 'Brazil', flag: '🇧🇷', endpoint: '/br.htm' },
  'IO': { code: 'IO', name: 'British Indian Ocean Territory', flag: '🇮🇴', endpoint: '/io.htm' },
  'BN': { code: 'BN', name: 'Brunei Darussalam', flag: '🇧🇳', endpoint: '/bn.htm' },
  'BG': { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', endpoint: '/bg.htm' },
  'BF': { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', endpoint: '/bf.htm' },
  'BI': { code: 'BI', name: 'Burundi', flag: '🇧🇮', endpoint: '/bi.htm' },
  'KH': { code: 'KH', name: 'Cambodia', flag: '🇰🇭', endpoint: '/kh.htm' },
  'CM': { code: 'CM', name: 'Cameroon', flag: '🇨🇲', endpoint: '/cm.htm' },
  'CA': { code: 'CA', name: 'Canada', flag: '🇨🇦', endpoint: '/ca.htm' },
  'CV': { code: 'CV', name: 'Cape Verde', flag: '🇨🇻', endpoint: '/cv.htm' },
  'KY': { code: 'KY', name: 'Cayman Islands', flag: '🇰🇾', endpoint: '/ky.htm' },
  'CF': { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', endpoint: '/cf.htm' },
  'TD': { code: 'TD', name: 'Chad', flag: '🇹🇩', endpoint: '/td.htm' },
  'CL': { code: 'CL', name: 'Chile', flag: '🇨🇱', endpoint: '/cl.htm' },
  'CN': { code: 'CN', name: 'China', flag: '🇨🇳', endpoint: '/cn.htm' },
  'CX': { code: 'CX', name: 'Christmas Island', flag: '🇨🇽', endpoint: '/cx.htm' },
  'CC': { code: 'CC', name: 'Cocos (Keeling) Islands', flag: '🇨🇨', endpoint: '/cc.htm' },
  'CO': { code: 'CO', name: 'Colombia', flag: '🇨🇴', endpoint: '/co.htm' },
  'KM': { code: 'KM', name: 'Comoros', flag: '🇰🇲', endpoint: '/km.htm' },
  'CG': { code: 'CG', name: 'Congo', flag: '🇨🇬', endpoint: '/cg.htm' },
  'CD': { code: 'CD', name: 'Congo, Democratic Republic of', flag: '🇨🇩', endpoint: '/cd.htm' },
  'CK': { code: 'CK', name: 'Cook Islands', flag: '🇨🇰', endpoint: '/ck.htm' },
  'CR': { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', endpoint: '/cr.htm' },
  'CI': { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', endpoint: '/ci.htm' },
  'HR': { code: 'HR', name: 'Croatia', flag: '🇭🇷', endpoint: '/hr.htm' },
  'CU': { code: 'CU', name: 'Cuba', flag: '🇨🇺', endpoint: '/cu.htm' },
  'CW': { code: 'CW', name: 'Curaçao', flag: '🇨🇼', endpoint: '/cw.htm' },
  'CY': { code: 'CY', name: 'Cyprus', flag: '🇨🇾', endpoint: '/cy.htm' },
  'CZ': { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', endpoint: '/cz.htm' },
  'DK': { code: 'DK', name: 'Denmark', flag: '🇩🇰', endpoint: '/dk.htm' },
  'DJ': { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', endpoint: '/dj.htm' },
  'DM': { code: 'DM', name: 'Dominica', flag: '🇩🇲', endpoint: '/dm.htm' },
  'DO': { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', endpoint: '/do.htm' },
  'EC': { code: 'EC', name: 'Ecuador', flag: '🇪🇨', endpoint: '/ec.htm' },
  'EG': { code: 'EG', name: 'Egypt', flag: '🇪🇬', endpoint: '/eg.htm' },
  'SV': { code: 'SV', name: 'El Salvador', flag: '🇸🇻', endpoint: '/sv.htm' },
  'GQ': { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', endpoint: '/gq.htm' },
  'ER': { code: 'ER', name: 'Eritrea', flag: '🇪🇷', endpoint: '/er.htm' },
  'EE': { code: 'EE', name: 'Estonia', flag: '🇪🇪', endpoint: '/ee.htm' },
  'ET': { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', endpoint: '/et.htm' },
  'FK': { code: 'FK', name: 'Falkland Islands', flag: '🇫🇰', endpoint: '/fk.htm' },
  'FO': { code: 'FO', name: 'Faroe Islands', flag: '🇫🇴', endpoint: '/fo.htm' },
  'FJ': { code: 'FJ', name: 'Fiji', flag: '🇫🇯', endpoint: '/fj.htm' },
  'FI': { code: 'FI', name: 'Finland', flag: '🇫🇮', endpoint: '/fi.htm' },
  'FR': { code: 'FR', name: 'France', flag: '🇫🇷', endpoint: '/fr.htm' },
  'GF': { code: 'GF', name: 'French Guiana', flag: '🇬🇫', endpoint: '/gf.htm' },
  'PF': { code: 'PF', name: 'French Polynesia', flag: '🇵🇫', endpoint: '/pf.htm' },
  'TF': { code: 'TF', name: 'French Southern Territories', flag: '🇹🇫', endpoint: '/tf.htm' },
  'GA': { code: 'GA', name: 'Gabon', flag: '🇬🇦', endpoint: '/ga.htm' },
  'GM': { code: 'GM', name: 'Gambia', flag: '🇬🇲', endpoint: '/gm.htm' },
  'GE': { code: 'GE', name: 'Georgia', flag: '🇬🇪', endpoint: '/ge.htm' },
  'DE': { code: 'DE', name: 'Germany', flag: '🇩🇪', endpoint: '/de.htm' },
  'GH': { code: 'GH', name: 'Ghana', flag: '🇬🇭', endpoint: '/gh.htm' },
  'GI': { code: 'GI', name: 'Gibraltar', flag: '🇬🇮', endpoint: '/gi.htm' },
  'GR': { code: 'GR', name: 'Greece', flag: '🇬🇷', endpoint: '/gr.htm' },
  'GL': { code: 'GL', name: 'Greenland', flag: '🇬🇱', endpoint: '/gl.htm' },
  'GD': { code: 'GD', name: 'Grenada', flag: '🇬🇩', endpoint: '/gd.htm' },
  'GP': { code: 'GP', name: 'Guadeloupe', flag: '🇬🇵', endpoint: '/gp.htm' },
  'GU': { code: 'GU', name: 'Guam', flag: '🇬🇺', endpoint: '/gu.htm' },
  'GT': { code: 'GT', name: 'Guatemala', flag: '🇬🇹', endpoint: '/gt.htm' },
  'GG': { code: 'GG', name: 'Guernsey', flag: '🇬🇬', endpoint: '/gg.htm' },
  'GN': { code: 'GN', name: 'Guinea', flag: '🇬🇳', endpoint: '/gn.htm' },
  'GW': { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', endpoint: '/gw.htm' },
  'GY': { code: 'GY', name: 'Guyana', flag: '🇬🇾', endpoint: '/gy.htm' },
  'HT': { code: 'HT', name: 'Haiti', flag: '🇭🇹', endpoint: '/ht.htm' },
  'HM': { code: 'HM', name: 'Heard Island and McDonald Islands', flag: '🇭🇲', endpoint: '/hm.htm' },
  'VA': { code: 'VA', name: 'Holy See (Vatican City State)', flag: '🇻🇦', endpoint: '/va.htm' },
  'HN': { code: 'HN', name: 'Honduras', flag: '🇭🇳', endpoint: '/hn.htm' },
  'HK': { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', endpoint: '/hk.htm' },
  'HU': { code: 'HU', name: 'Hungary', flag: '🇭🇺', endpoint: '/hu.htm' },
  'IS': { code: 'IS', name: 'Iceland', flag: '🇮🇸', endpoint: '/is.htm' },
  'IN': { code: 'IN', name: 'India', flag: '🇮🇳', endpoint: '/in.htm' },
  'ID': { code: 'ID', name: 'Indonesia', flag: '🇮🇩', endpoint: '/id.htm' },
  'IR': { code: 'IR', name: 'Iran', flag: '🇮🇷', endpoint: '/ir.htm' },
  'IQ': { code: 'IQ', name: 'Iraq', flag: '🇮🇶', endpoint: '/iq.htm' },
  'IE': { code: 'IE', name: 'Ireland', flag: '🇮🇪', endpoint: '/ie.htm' },
  'IM': { code: 'IM', name: 'Isle of Man', flag: '🇮🇲', endpoint: '/im.htm' },
  'IL': { code: 'IL', name: 'Israel', flag: '🇮🇱', endpoint: '/il.htm' },
  'IT': { code: 'IT', name: 'Italy', flag: '🇮🇹', endpoint: '/it.htm' },
  'JM': { code: 'JM', name: 'Jamaica', flag: '🇯🇲', endpoint: '/jm.htm' },
  'JP': { code: 'JP', name: 'Japan', flag: '🇯🇵', endpoint: '/jp.htm' },
  'JE': { code: 'JE', name: 'Jersey', flag: '🇬🇧', endpoint: '/je.htm' },
  'JO': { code: 'JO', name: 'Jordan', flag: '🇯🇴', endpoint: '/jo.htm' },
  'KZ': { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', endpoint: '/kz.htm' },
  'KE': { code: 'KE', name: 'Kenya', flag: '🇰🇪', endpoint: '/ke.htm' },
  'KI': { code: 'KI', name: 'Kiribati', flag: '🇰🇮', endpoint: '/ki.htm' },
  'KP': { code: 'KP', name: "Korea, Democratic People's Republic of", flag: '🇰🇵', endpoint: '/kp.htm' },
  'KR': { code: 'KR', name: 'Korea, Republic of', flag: '🇰🇷', endpoint: '/kr.htm' },
  'KW': { code: 'KW', name: 'Kuwait', flag: '🇰🇼', endpoint: '/kw.htm' },
  'KG': { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', endpoint: '/kg.htm' },
  'LA': { code: 'LA', name: "Lao People's Democratic Republic", flag: '🇱🇦', endpoint: '/la.htm' },
  'LV': { code: 'LV', name: 'Latvia', flag: '🇱🇻', endpoint: '/lv.htm' },
  'LB': { code: 'LB', name: 'Lebanon', flag: '🇱🇧', endpoint: '/lb.htm' },
  'LS': { code: 'LS', name: 'Lesotho', flag: '🇱🇸', endpoint: '/ls.htm' },
  'LR': { code: 'LR', name: 'Liberia', flag: '🇱🇷', endpoint: '/lr.htm' },
  'LY': { code: 'LY', name: 'Libya', flag: '🇱🇾', endpoint: '/ly.htm' },
  'LI': { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', endpoint: '/li.htm' },
  'LT': { code: 'LT', name: 'Lithuania', flag: '🇱🇹', endpoint: '/lt.htm' },
  'LU': { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', endpoint: '/lu.htm' },
  'MO': { code: 'MO', name: 'Macao', flag: '🇲🇴', endpoint: '/mo.htm' },
  'MK': { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', endpoint: '/mk.htm' },
  'MG': { code: 'MG', name: 'Madagascar', flag: '🇲🇬', endpoint: '/mg.htm' },
  'MW': { code: 'MW', name: 'Malawi', flag: '🇲🇼', endpoint: '/mw.htm' },
  'MY': { code: 'MY', name: 'Malaysia', flag: '🇲🇾', endpoint: '/my.htm' },
  'MV': { code: 'MV', name: 'Maldives', flag: '🇲🇻', endpoint: '/mv.htm' },
  'ML': { code: 'ML', name: 'Mali', flag: '🇲🇱', endpoint: '/ml.htm' },
  'MT': { code: 'MT', name: 'Malta', flag: '🇲🇹', endpoint: '/mt.htm' },
  'MH': { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', endpoint: '/mh.htm' },
  'MQ': { code: 'MQ', name: 'Martinique', flag: '🇲🇶', endpoint: '/mq.htm' },
  'MR': { code: 'MR', name: 'Mauritania', flag: '🇲🇷', endpoint: '/mr.htm' },
  'MU': { code: 'MU', name: 'Mauritius', flag: '🇲🇺', endpoint: '/mu.htm' },
  'YT': { code: 'YT', name: 'Mayotte', flag: '🇾🇹', endpoint: '/yt.htm' },
  'MX': { code: 'MX', name: 'Mexico', flag: '🇲🇽', endpoint: '/mx.htm' },
  'FM': { code: 'FM', name: 'Micronesia', flag: '🇫🇲', endpoint: '/fm.htm' },
  'MD': { code: 'MD', name: 'Moldova', flag: '🇲🇩', endpoint: '/md.htm' },
  'MC': { code: 'MC', name: 'Monaco', flag: '🇲🇨', endpoint: '/mc.htm' },
  'MN': { code: 'MN', name: 'Mongolia', flag: '🇲🇳', endpoint: '/mn.htm' },
  'ME': { code: 'ME', name: 'Montenegro', flag: '🇲🇪', endpoint: '/me.htm' },
  'MS': { code: 'MS', name: 'Montserrat', flag: '🇲🇸', endpoint: '/ms.htm' },
  'MA': { code: 'MA', name: 'Morocco', flag: '🇲🇦', endpoint: '/ma.htm' },
  'MZ': { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', endpoint: '/mz.htm' },
  'MM': { code: 'MM', name: 'Myanmar', flag: '🇲🇲', endpoint: '/mm.htm' },
  'NA': { code: 'NA', name: 'Namibia', flag: '🇳🇦', endpoint: '/na.htm' },
  'NR': { code: 'NR', name: 'Nauru', flag: '🇳🇷', endpoint: '/nr.htm' },
  'NP': { code: 'NP', name: 'Nepal', flag: '🇳🇵', endpoint: '/np.htm' },
  'NL': { code: 'NL', name: 'Netherlands', flag: '🇳🇱', endpoint: '/nl.htm' },
  'NC': { code: 'NC', name: 'New Caledonia', flag: '🇳🇨', endpoint: '/nc.htm' },
  'NZ': { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', endpoint: '/nz.htm' },
  'NI': { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', endpoint: '/ni.htm' },
  'NE': { code: 'NE', name: 'Niger', flag: '🇳🇪', endpoint: '/ne.htm' },
  'NG': { code: 'NG', name: 'Nigeria', flag: '🇳🇬', endpoint: '/ng.htm' },
  'NU': { code: 'NU', name: 'Niue', flag: '🇳🇺', endpoint: '/nu.htm' },
  'NF': { code: 'NF', name: 'Norfolk Island', flag: '🇳🇫', endpoint: '/nf.htm' },
  'MP': { code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵', endpoint: '/mp.htm' },
  'NO': { code: 'NO', name: 'Norway', flag: '🇳🇴', endpoint: '/no.htm' },
  'OM': { code: 'OM', name: 'Oman', flag: '🇴🇲', endpoint: '/om.htm' },
  'PK': { code: 'PK', name: 'Pakistan', flag: '🇵🇰', endpoint: '/pk.htm' },
  'PW': { code: 'PW', name: 'Palau', flag: '🇵🇼', endpoint: '/pw.htm' },
  'PS': { code: 'PS', name: 'Palestine', flag: '🇵🇸', endpoint: '/ps.htm' },
  'PA': { code: 'PA', name: 'Panama', flag: '🇵🇦', endpoint: '/pa.htm' },
  'PG': { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', endpoint: '/pg.htm' },
  'PY': { code: 'PY', name: 'Paraguay', flag: '🇵🇾', endpoint: '/py.htm' },
  'PE': { code: 'PE', name: 'Peru', flag: '🇵🇪', endpoint: '/pe.htm' },
  'PH': { code: 'PH', name: 'Philippines', flag: '🇵🇭', endpoint: '/ph.htm' },
  'PN': { code: 'PN', name: 'Pitcairn', flag: '🇵🇳', endpoint: '/pn.htm' },
  'PL': { code: 'PL', name: 'Poland', flag: '🇵🇱', endpoint: '/pl.htm' },
  'PT': { code: 'PT', name: 'Portugal', flag: '🇵🇹', endpoint: '/pt.htm' },
  'PR': { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷', endpoint: '/pr.htm' },
  'QA': { code: 'QA', name: 'Qatar', flag: '🇶🇦', endpoint: '/qa.htm' },
  'RE': { code: 'RE', name: 'Réunion', flag: '🇷🇪', endpoint: '/re.htm' },
  'RO': { code: 'RO', name: 'Romania', flag: '🇷🇴', endpoint: '/ro.htm' },
  'RU': { code: 'RU', name: 'Russian Federation', flag: '🇷🇺', endpoint: '/ru.htm' },
  'RW': { code: 'RW', name: 'Rwanda', flag: '🇷🇼', endpoint: '/rw.htm' },
  'BL': { code: 'BL', name: 'Saint Barthélemy', flag: '🇧🇱', endpoint: '/bl.htm' },
  'SH': { code: 'SH', name: 'Saint Helena', flag: '🇸🇭', endpoint: '/sh.htm' },
  'KN': { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', endpoint: '/kn.htm' },
  'LC': { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', endpoint: '/lc.htm' },
  'MF': { code: 'MF', name: 'Saint Martin (French part)', flag: '🇲🇫', endpoint: '/mf.htm' },
  'PM': { code: 'PM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲', endpoint: '/pm.htm' },
  'VC': { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', endpoint: '/vc.htm' },
  'WS': { code: 'WS', name: 'Samoa', flag: '🇼🇸', endpoint: '/ws.htm' },
  'SM': { code: 'SM', name: 'San Marino', flag: '🇸🇲', endpoint: '/sm.htm' },
  'ST': { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', endpoint: '/st.htm' },
  'SA': { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', endpoint: '/sa.htm' },
  'SN': { code: 'SN', name: 'Senegal', flag: '🇸🇳', endpoint: '/sn.htm' },
  'RS': { code: 'RS', name: 'Serbia', flag: '🇷🇸', endpoint: '/rs.htm' },
  'SC': { code: 'SC', name: 'Seychelles', flag: '🇸🇨', endpoint: '/sc.htm' },
  'SL': { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', endpoint: '/sl.htm' },
  'SG': { code: 'SG', name: 'Singapore', flag: '🇸🇬', endpoint: '/sg.htm' },
  'SX': { code: 'SX', name: 'Sint Maarten (Dutch part)', flag: '🇸🇽', endpoint: '/sx.htm' },
  'SK': { code: 'SK', name: 'Slovakia', flag: '🇸🇰', endpoint: '/sk.htm' },
  'SI': { code: 'SI', name: 'Slovenia', flag: '🇸🇮', endpoint: '/si.htm' },
  'SB': { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', endpoint: '/sb.htm' },
  'SO': { code: 'SO', name: 'Somalia', flag: '🇸🇴', endpoint: '/so.htm' },
  'ZA': { code: 'ZA', name: 'South Africa', flag: '🇿🇦', endpoint: '/za.htm' },
  'GS': { code: 'GS', name: 'South Georgia and the South Sandwich Islands', flag: '🇿🇦', endpoint: '/gs.htm' },
  'SS': { code: 'SS', name: 'South Sudan', flag: '🇸🇸', endpoint: '/ss.htm' },
  'ES': { code: 'ES', name: 'Spain', flag: '🇪🇸', endpoint: '/es.htm' },
  'LK': { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', endpoint: '/lk.htm' },
  'SD': { code: 'SD', name: 'Sudan', flag: '🇸🇩', endpoint: '/sd.htm' },
  'SR': { code: 'SR', name: 'Suriname', flag: '🇸🇷', endpoint: '/sr.htm' },
  'SJ': { code: 'SJ', name: 'Svalbard and Jan Mayen', flag: '🇳🇴', endpoint: '/sj.htm' },
  'SE': { code: 'SE', name: 'Sweden', flag: '🇸🇪', endpoint: '/se.htm' },
  'CH': { code: 'CH', name: 'Switzerland', flag: '🇨🇭', endpoint: '/ch.htm' },
  'SY': { code: 'SY', name: 'Syrian Arab Republic', flag: '🇸🇾', endpoint: '/sy.htm' },
  'TW': { code: 'TW', name: 'Taiwan', flag: '🇹🇼', endpoint: '/tw.htm' },
  'TJ': { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', endpoint: '/tj.htm' },
  'TZ': { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', endpoint: '/tz.htm' },
  'TH': { code: 'TH', name: 'Thailand', flag: '🇹🇭', endpoint: '/th.htm' },
  'TL': { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', endpoint: '/tl.htm' },
  'TG': { code: 'TG', name: 'Togo', flag: '🇹🇬', endpoint: '/tg.htm' },
  'TK': { code: 'TK', name: 'Tokelau', flag: '🇹🇰', endpoint: '/tk.htm' },
  'TO': { code: 'TO', name: 'Tonga', flag: '🇹🇴', endpoint: '/to.htm' },
  'TT': { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', endpoint: '/tt.htm' },
  'TN': { code: 'TN', name: 'Tunisia', flag: '🇹🇳', endpoint: '/tn.htm' },
  'TR': { code: 'TR', name: 'Turkey', flag: '🇹🇷', endpoint: '/tr.htm' },
  'TM': { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', endpoint: '/tm.htm' },
  'TC': { code: 'TC', name: 'Turks and Caicos Islands', flag: '🇹🇨', endpoint: '/tc.htm' },
  'TV': { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', endpoint: '/tv.htm' },
  'UG': { code: 'UG', name: 'Uganda', flag: '🇺🇬', endpoint: '/ug.htm' },
  'UA': { code: 'UA', name: 'Ukraine', flag: '🇺🇦', endpoint: '/ua.htm' },
  'AE': { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', endpoint: '/ae.htm' },
  'GB': { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', endpoint: '/gb.htm' },
  'US': { code: 'US', name: 'United States', flag: '🇺🇸', endpoint: '/us.htm' },
  'UM': { code: 'UM', name: 'United States Minor Outlying Islands', flag: '🇺🇲', endpoint: '/um.htm' },
  'UY': { code: 'UY', name: 'Uruguay', flag: '🇺🇾', endpoint: '/uy.htm' },
  'UZ': { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', endpoint: '/uz.htm' },
  'VU': { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', endpoint: '/vu.htm' },
  'VE': { code: 'VE', name: 'Venezuela', flag: '🇻🇪', endpoint: '/ve.htm' },
  'VN': { code: 'VN', name: 'Viet Nam', flag: '🇻🇳', endpoint: '/vn.htm' },
  'VG': { code: 'VG', name: 'Virgin Islands, British', flag: '🇻🇬', endpoint: '/vg.htm' },
  'VI': { code: 'VI', name: 'Virgin Islands, U.S.', flag: '🇻🇮', endpoint: '/vi.htm' },
  'WF': { code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫', endpoint: '/wf.htm' },
  'EH': { code: 'EH', name: 'Western Sahara', flag: '🇪🇭', endpoint: '/eh.htm' },
  'YE': { code: 'YE', name: 'Yemen', flag: '🇾🇪', endpoint: '/ye.htm' },
  'ZM': { code: 'ZM', name: 'Zambia', flag: '🇿🇲', endpoint: '/zm.htm' },
  'ZW': { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', endpoint: '/zw.htm' }
} as const;


export const FUNCTION_CODES = {
  '1': 'Port',
  '2': 'Rail Terminal',
  '3': 'Road Terminal',
  '4': 'Airport',
  '5': 'Postal Exchange',
  '6': 'Multimodal Functions',
  '7': 'Fixed Transport Functions',
  'B': 'Border Crossing',
};

export const REQUEST_HEADERS = {
  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  'Cache-Control': 'no-cache',
  'Pragma': 'no-cache'
};

export const STATUS_CODES = {
  'AA': 'Approved by competent national government agency',
  'AC': 'Approved by Customs Authority',
  'AF': 'Approved by national facilitation body',
  'AI': 'Code adopted by international organization (IATA or ECLAC)',
  'AS': 'Approved by national standardization body',
  'RL': 'Recognized location - Existence and representation of location name confirmed by check against nominated gazetteer or other reference work',
  'RN': 'Request from credible national sources for locations in their own country',
  'RQ': 'Request under consideration',
  'RR': 'Request rejected',
  'QQ': 'Original entry not verified since date indicated',
  'XX': 'Entry to be removed from the next issue of UN/LOCODE'
}; 